language: python
python:
  - "3.5"
  - "2.7"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
script:
  - paver test # or py.test for Python versions 3.5 and below
  - paver doc_html
